# Tabla de tipos pokemon daño 2x, 1x daño normal, 0.5x resistente y 0 es inmune
info_types = {
    "normal": {
        "fighting": 2.0, 
        "ghost": 0.0,
        "steel":1,
        "water":1,
        "bug":1,
        "dragon":1,
        "electric":1,
        "fire":1,
        "fairy":1,
        "ice":1,
        "normal":1,
        "grass":1,
        "psychic":1,
        "rock":1,
        "dark":1,
        "ground":1,
        "poison":1,
        "flying":1,
    },
    "fire": {
        "water": 2.0,
        "ground": 2.0,
        "rock": 2.0,
        "bug": 0.5,
        "grass": 0.5,
        "ice": 0.5,
        "steel": 0.5,
        "dragon":1,
        "electric":1,
        "ghost":1,
        "fire":1,
        "fairy":1,
        "fighting":1,
        "normal":1,
        "psychic":1,
        "dark":1,
        "poison":1,
        "flying":1,
    },
    "water": {
        "electric": 2.0,
        "grass": 2.0,
        "fire": 0.5,
        "water": 0.5,
        "ice": 0.5,
        "steel": 0.5,
        "water":1,
        "bug":1,
        "dragon":1,
        "fairy":1,
        "fighting":1,
        "normal":1,
        "psychic":1,
        "rock":1,
        "dark":1,
        "ground":1,
        "poison":1,
        "flying":1,
        "ghost": 1,
    },
    "electric": {
        "ground": 2.0,
        "flying": 0.5,
        "electric": 0.5,
        "steel": 0.5,
        "water":1,
        "bug":1,
        "dragon":1,
        "fire":1,
        "fairy":1,
        "ice":1,
        "fighting":1,
        "normal":1,
        "grass":1,
        "psychic":1,
        "rock":1,
        "dark":1,
        "poison":1,
        "ghost": 1,
    },
    "grass": {
        "fire": 2.0,
        "ice": 2.0,
        "poison": 2.0,
        "flying": 2.0,
        "bug": 2.0,
        "water": 0.5,
        "electric": 0.5,
        "grass": 0.5,
        "ground": 0.5,
        "steel":1,
        "dragon":1,
        "fairy":1,
        "fighting":1,
        "normal":1,
        "psychic":1,
        "rock":1,
        "dark":1,
        "ghost": 1,
    },
    "ice": {
        "fire": 2.0,
        "fighting": 2.0,
        "rock": 2.0,
        "steel": 2.0,
        "ice": 0.5,
        "water":1,
        "bug":1,
        "dragon":1,
        "electric":1,
        "fairy":1,
        "normal":1,
        "grass":1,
        "psychic":1,
        "dark":1,
        "ground":1,
        "poison":1,
        "flying":1,
        "ghost": 1,
    },
    "fighting": {
        "flying": 2.0,
        "psychic": 2.0,
        "fairy": 2.0,
        "bug": 0.5,
        "rock": 0.5,
        "dark": 0.5,
        "steel":1,
        "water":1,
        "dragon":1,
        "electric":1,
        "fire":1,
        "ice":1,
 	    "fighting":1,
        "normal":1,
        "grass":1,
        "ground":1,
        "poison":1,
        "ghost": 1,
    },
    "poison": {
        "ground": 2.0,
        "psychic": 2.0,
        "grass": 0.5,
        "fighting": 0.5,
        "poison": 0.5,
        "bug": 0.5,
        "fairy": 0.5,
        "steel":1,
        "water":1,
        "dragon":1,
        "electric":1,
        "fire":1,
        "ice":1,
        "normal":1,
        "rock":1,
        "dark":1,
        "flying":1,
        "ghost": 1,
    },
    "ground": {
        "water": 2.0,
        "grass": 2.0,
        "ice": 2.0,
        "poison": 0.5,
        "rock": 0.5,
        "steel":1,
        "bug":1,
        "dragon":1,
        "electric":1,
        "fire":1,
        "fairy":1,
 	    "fighting":1,
        "normal":1,
        "psychic":1,
        "dark":1,
        "ground":1,
        "flying":1,
        "ghost": 1,
    },
    "flying": {
        "electric": 2.0,
        "ice": 2.0,
        "rock": 2.0,
        "grass": 0.5,
        "fighting": 0.5,
        "bug": 0.5,
        "steel":1,
        "water":1,
        "dragon":1,
        "fire":1,
        "fairy":1,
        "normal":1,
        "psychic":1,
        "dark":1,
        "ground":1,
        "poison":1,
        "flying":1,
        "ghost": 1,
    },
    "psychic": {
        "bug": 2.0,
        "ghost": 2.0,
        "dark": 2.0,
        "fighting": 0.5,
        "psychic": 0.5,
        "steel":1,
        "water":1,
        "dragon":1,
        "electric":1,
        "fire":1,
        "fairy":1,
        "ice":1,
        "normal":1,
        "grass":1,
        "rock":1,
        "ground":1,
        "poison":1,
        "flying":1,
    },
    "bug": {
        "fire": 2.0,
        "flying": 2.0,
        "rock": 2.0,
        "grass": 0.5,
        "fighting": 0.5,
        "ground": 0.5,
        "steel":1,
        "water":1,
        "bug":1,
        "dragon":1,
        "electric":1,
        "fairy":1,
        "ice":1,
        "normal":1,
        "psychic":1,
        "dark":1,
        "poison":1,
        "ghost": 1,
    },
    "rock": {
        "water": 2.0,
        "grass": 2.0,
        "fighting": 2.0,
        "ground": 2.0,
        "steel": 2.0,
        "normal": 0.5,
        "fire": 0.5,
        "poison": 0.5,
        "flying": 0.5,
        "bug":1,
        "dragon":1,
        "electric":1,
        "fairy":1,
        "ice":1,
        "psychic":1,
        "rock":1,
        "dark":1,
        "ghost": 1,
    },
    "ghost": {
        "ghost": 2.0,
        "dark": 2.0,
        "poison": 0.5,
        "bug": 0.5,
        "fighting": 0.0,
        "normal": 0.0,
        "steel":1,
        "water":1,
        "dragon":1,
        "electric":1,
        "fire":1,
        "fairy":1,
        "ice":1,
        "grass":1,
        "psychic":1,
        "rock":1,
        "ground":1,
        "flying":1,
    },
    "dragon": {
        "ice": 2.0,
        "dragon": 2.0,
        "fairy": 2.0,
        "fire": 0.5,
        "water": 0.5,
        "electric": 0.5,
        "grass": 0.5,
        "steel":1,
        "bug":1,
 	    "fighting":1,
        "normal":1,
        "psychic":1,
        "rock":1,
        "dark":1,
        "ground":1,
        "poison":1,
        "flying":1,
        "ghost": 1,

    },
    "dark": {
        "fighting": 2.0,
        "bug": 2.0,
        "fairy": 2.0,
        "ghost": 0.5,
        "psychic": 0.0,
        "dark": 0.5,
        "steel":1,
        "water":1,
        "dragon":1,
        "electric":1,
        "fire":1,
        "ice":1,
        "normal":1,
        "grass":1,
        "rock":1,
        "ground":1,
        "poison":1,
        "flying":1,
    },
    "steel": {
        "fire": 2.0,
        "fighting": 2.0,
        "ground": 2.0,
        "normal": 0.5,
        "grass": 0.5,
        "ice": 0.5,
        "flying": 0.5,
        "psychic": 0.5,
        "bug": 0.5,
        "rock": 0.5,
        "dragon": 0.5,
        "steel": 0.5,
        "fairy": 0.5,
        "water":1,
        "electric":1,
        "dark":1,
        "poison":1,
        "ghost": 1,
    },
    "fairy": {
        "poison": 2.0,
        "steel": 2.0,
        "fighting": 0.5,
        "bug": 0.5,
        "dark": 0.5,
        "dragon": 0.0,
        "water":1,
        "electric":1,
        "fire":1,
        "fairy":1,
        "ice":1,
        "normal":1,
        "grass":1,
        "psychic":1,
        "rock":1,
        "ground":1,
        "flying":1,
        "ghost": 1,
    },
}